### PR TITLE
Add version to package.json

### PR DESCRIPTION
**Pull request by bxmmm1**
Update package.json so that this repository can be installed using yarn

### CODE REVIEW

**Review by Le-Wind — APPROVED** [review]

**Review by Le-Wind — APPROVED** [review]

**Comment by novaknole** [comment]
Bump as we need this desparately because we're not using submodules.

**Comment by Le-Wind** [comment]
> Hi! Just a gentle reminder to merge this PR when convenient. Thanks!

Could you please show me the steps to merge? Thank you!

**Comment by bxmmm1** [comment]
@ericglau ?

**Review by ericglau — APPROVED** [review]

**Comment by ericglau** [comment]
Thanks for the PR and comments!  We may need to make some changes to how the package is set up before releasing this to NPM, but this PR looks good in the meantime.

**Pull request merged**
